# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-01 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='neigbourhood_id',
            new_name='neighbourhood_id',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='neigbourhood_id',
            new_name='neighbourhood_id',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='neigbourhood_id',
            new_name='neighbourhood_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='neigbourhood_id',
            new_name='neighbourhood_id',
        ),
    ]
