# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-03 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0002_auto_20190601_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='../static/images/noimage.svg', null=True, upload_to='images/'),
        ),
    ]
